// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnse7GGjWg5ADEnIRN3ydQqNO3IAY_sYs',
    appId: '1:749052554064:web:76e1a55cfee3abd0335a55',
    messagingSenderId: '749052554064',
    projectId: 'chatbiternd',
    authDomain: 'chatbiternd.firebaseapp.com',
    storageBucket: 'chatbiternd.appspot.com',
    measurementId: 'G-SEFD9YMJFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJBa9qupZZgGJeOuBKahT_eXM-XyKsVj8',
    appId: '1:749052554064:android:dbab3c3d4e42b34e335a55',
    messagingSenderId: '749052554064',
    projectId: 'chatbiternd',
    storageBucket: 'chatbiternd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5TxjQfOlp8reUR1WGpLCm5uQIminV8x8',
    appId: '1:749052554064:ios:59c17ad287c91fee335a55',
    messagingSenderId: '749052554064',
    projectId: 'chatbiternd',
    storageBucket: 'chatbiternd.appspot.com',
    iosClientId: '749052554064-k4i8lrg4k7vbrt1bc2oo4mbc9q3dnm0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatBite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5TxjQfOlp8reUR1WGpLCm5uQIminV8x8',
    appId: '1:749052554064:ios:59c17ad287c91fee335a55',
    messagingSenderId: '749052554064',
    projectId: 'chatbiternd',
    storageBucket: 'chatbiternd.appspot.com',
    iosClientId: '749052554064-k4i8lrg4k7vbrt1bc2oo4mbc9q3dnm0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatBite',
  );
}
